# Generated by Django 5.2.7 on 2025-10-16 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('reglamento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(help_text='Ej: Cancha 1 - Central', max_length=100),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='tipo_cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canchas', to='reservas.tipocancha'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='tipocancha',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o reglas del tipo de cancha.', null=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pago', serialize=False, to='reservas.reserva')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('ONLINE', 'Online'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cancha'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='reservas', to='reservas.servicio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('cancha', 'fecha_hora_inicio')},
        ),
    ]
