# Generated by Django 5.2.7 on 2025-10-19 21:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import reservas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_servicio_torneo_alter_cancha_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancha',
            options={'ordering': ['nombre'], 'verbose_name': 'Cancha', 'verbose_name_plural': 'Canchas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='tipocancha',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Cancha', 'verbose_name_plural': 'Tipos de Cancha'},
        ),
        migrations.AlterModelOptions(
            name='torneo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Torneo', 'verbose_name_plural': 'Torneos'},
        ),
        migrations.AddField(
            model_name='cancha',
            name='activa',
            field=models.BooleanField(default=True, help_text='Cancha disponible para reservas'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='capacidad_personas',
            field=models.PositiveIntegerField(default=10, help_text='Capacidad máxima de personas', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Cliente activo en el sistema'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.CharField(blank=True, help_text='Número de comprobante o transacción', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la reserva', null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Servicio disponible'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='precio_por_hora',
            field=models.DecimalField(decimal_places=2, help_text='Precio por hora en pesos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(help_text='DNI argentino de 7 u 8 dígitos', max_length=10, unique=True, validators=[reservas.models.validar_dni_argentino], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(help_text='Email único para el cliente', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Número de teléfono válido', max_length=20, validators=[reservas.models.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('ONLINE', 'Online'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='costo_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
