# Generated by Django 5.2.7 on 2025-10-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_cancha_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
