# Generated by Django 5.2.7 on 2025-10-20 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_remove_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de inscripción al torneo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del torneo', null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='max_equipos',
            field=models.PositiveIntegerField(blank=True, help_text='Máximo de equipos permitidos (opcional)', null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='torneo',
            name='premio',
            field=models.CharField(blank=True, help_text='Premio del torneo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
