# Generated by Django 5.2.7 on 2025-10-20 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_torneo_costo_inscripcion_torneo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, help_text='Monto total del pago (máximo: $999,999.99)', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999.99)]),
        ),
    ]
