# Generated by Django 5.2.7 on 2025-10-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_pago_monto_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del equipo', max_length=150)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Equipo activo en el torneo')),
                ('logo', models.CharField(blank=True, help_text='Emoji o icono para el equipo (opcional)', max_length=10, null=True)),
                ('capitan', models.ForeignKey(blank=True, help_text='Capitán del equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_capitaneados', to='reservas.cliente')),
                ('jugadores', models.ManyToManyField(blank=True, help_text='Jugadores del equipo', related_name='equipos', to='reservas.cliente')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='reservas.torneo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['torneo', 'nombre'],
                'unique_together': {('torneo', 'nombre')},
            },
        ),
    ]
