# Generated by Django 5.2.7 on 2025-10-20 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='max_equipos',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneo',
            name='equipos',
            field=models.ManyToManyField(blank=True, help_text='Equipos inscritos en el torneo', related_name='torneos', to='reservas.equipo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='estado',
            field=models.CharField(choices=[('INSCRIPCION', 'Abierto para Inscripciones'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='INSCRIPCION', help_text='Estado actual del torneo', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Equipo activo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(help_text='Nombre del equipo', max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='torneo',
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.PositiveIntegerField(help_text='Ronda del torneo (1=Primera ronda, 2=Semifinal, etc.)')),
                ('numero_partido', models.PositiveIntegerField(help_text='Número de partido dentro de la ronda')),
                ('resultado_equipo1', models.PositiveIntegerField(blank=True, help_text='Resultado del equipo 1', null=True)),
                ('resultado_equipo2', models.PositiveIntegerField(blank=True, help_text='Resultado del equipo 2', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADO', 'Finalizado'), ('WALKOVER', 'Walkover')], default='PENDIENTE', max_length=20)),
                ('fecha_hora', models.DateTimeField(blank=True, help_text='Fecha y hora del partido', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipo1', models.ForeignKey(blank=True, help_text='Primer equipo (puede ser null si viene de un partido anterior)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo1', to='reservas.equipo')),
                ('equipo2', models.ForeignKey(blank=True, help_text='Segundo equipo (puede ser null si viene de un partido anterior)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_como_equipo2', to='reservas.equipo')),
                ('ganador', models.ForeignKey(blank=True, help_text='Equipo ganador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='reservas.equipo')),
                ('partido_anterior_equipo1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguiente_partido_ganador1', to='reservas.partido')),
                ('partido_anterior_equipo2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguiente_partido_ganador2', to='reservas.partido')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='reservas.torneo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['torneo', 'ronda', 'numero_partido'],
                'unique_together': {('torneo', 'ronda', 'numero_partido')},
            },
        ),
    ]
