# Generated by Django 5.2.7 on 2025-10-21 13:35

from django.db import migrations


def cambiar_confirmada_a_pagada(apps, schema_editor):
    """Actualiza todos los registros con estado CONFIRMADA a PAGADA"""
    Reserva = apps.get_model('reservas', 'Reserva')
    Reserva.objects.filter(estado='CONFIRMADA').update(estado='PAGADA')


def revertir_pagada_a_confirmada(apps, schema_editor):
    """Revierte los cambios en caso de rollback"""
    Reserva = apps.get_model('reservas', 'Reserva')
    Reserva.objects.filter(estado='PAGADA').update(estado='CONFIRMADA')


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_equipo_options_alter_equipo_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(
            cambiar_confirmada_a_pagada,
            reverse_code=revertir_pagada_a_confirmada
        ),
    ]
