# Generated by Django 5.2.7 on 2025-10-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_cambiar_confirmada_a_pagada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='capitan',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='jugadores',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
    ]
