# Generated by Django 5.2.7 on 2025-11-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_remove_equipo_capitan_remove_equipo_jugadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mp_payment_id',
            field=models.CharField(blank=True, help_text='ID de pago de MercadoPago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_payment_type',
            field=models.CharField(blank=True, help_text='Tipo de pago en MercadoPago', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_preference_id',
            field=models.CharField(blank=True, help_text='ID de preferencia de MercadoPago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_status',
            field=models.CharField(blank=True, help_text='Estado del pago en MercadoPago', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('ONLINE', 'Online'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('MERCADOPAGO', 'MercadoPago')], max_length=20, null=True),
        ),
    ]
